name: Grade submission

on:
  workflow_call:
    inputs:
      result_url:
        description: Result API base URL
        required: false
        default: ""
        type: string

jobs:
  assignments:
    strategy:
      fail-fast: false
      matrix:
        include:
          - assignment: v1
            assignment_ref: assignment-v1
          - assignment: v2
            assignment_ref: assignment-v2
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/grade-assignment.yml
    with:
      assignment: ${{ matrix.assignment }}
      assignment_ref: ${{ matrix.assignment_ref }}
      result_url: ${{ inputs.result_url }}
